# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acc_db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='acc_db.proto',
  package='dhc',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x61\x63\x63_db.proto\x12\x03\x64hc\"b\n\x05\x61\x63\x63_t\x12\x0c\n\x04guid\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08serverid\x18\x03 \x01(\x05\x12\x14\n\x0c\x66\x65nghao_time\x18\x04 \x01(\x04\x12\x11\n\tlast_time\x18\x05 \x01(\x04')
)




_ACC_T = _descriptor.Descriptor(
  name='acc_t',
  full_name='dhc.acc_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='dhc.acc_t.guid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='dhc.acc_t.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverid', full_name='dhc.acc_t.serverid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fenghao_time', full_name='dhc.acc_t.fenghao_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_time', full_name='dhc.acc_t.last_time', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['acc_t'] = _ACC_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

acc_t = _reflection.GeneratedProtocolMessageType('acc_t', (_message.Message,), dict(
  DESCRIPTOR = _ACC_T,
  __module__ = 'acc_db_pb2'
  # @@protoc_insertion_point(class_scope:dhc.acc_t)
  ))
_sym_db.RegisterMessage(acc_t)


# @@protoc_insertion_point(module_scope)

acc_t_tmp = acc_t

from pgame.utils import proto_utils
class acc_t_db(proto_utils.object_t_db):
   def __init__(self):
      proto_utils.object_t_db.__init__(self, acc_t_tmp)
      self.children = [
         ]

proto_utils.make_db_proto(acc_t_db, acc_t_tmp)

acc_t = acc_t_db
