# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arena_room_db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arena_room_db.proto',
  package='dhc',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61rena_room_db.proto\x12\x03\x64hc\"\x9e\x02\n\x0c\x61rena_room_t\x12\x0c\n\x04guid\x18\x01 \x01(\x04\x12\x14\n\x0cplayer_guids\x18\x02 \x03(\x04\x12\x14\n\x0cplayer_names\x18\x03 \x03(\t\x12\x15\n\rplayer_levels\x18\x04 \x03(\x05\x12\x14\n\x0cplayer_icons\x18\x05 \x03(\x05\x12\x18\n\x10player_integrals\x18\x06 \x03(\x05\x12\x0e\n\x06is_npc\x18\x07 \x03(\x05\x12\x15\n\rplayer_powers\x18\x08 \x03(\x05\x12\x12\n\narena_wins\x18\t \x03(\x05\x12\x12\n\narena_nums\x18\n \x03(\x05\x12\x1a\n\x12\x61rena_list_indexes\x18\x0b \x03(\x05\x12\x0f\n\x07segment\x18\x0c \x01(\x05\x12\x11\n\tlast_time\x18\r \x01(\x04')
)




_ARENA_ROOM_T = _descriptor.Descriptor(
  name='arena_room_t',
  full_name='dhc.arena_room_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='dhc.arena_room_t.guid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_guids', full_name='dhc.arena_room_t.player_guids', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_names', full_name='dhc.arena_room_t.player_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_levels', full_name='dhc.arena_room_t.player_levels', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_icons', full_name='dhc.arena_room_t.player_icons', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_integrals', full_name='dhc.arena_room_t.player_integrals', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_npc', full_name='dhc.arena_room_t.is_npc', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_powers', full_name='dhc.arena_room_t.player_powers', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arena_wins', full_name='dhc.arena_room_t.arena_wins', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arena_nums', full_name='dhc.arena_room_t.arena_nums', index=9,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arena_list_indexes', full_name='dhc.arena_room_t.arena_list_indexes', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment', full_name='dhc.arena_room_t.segment', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_time', full_name='dhc.arena_room_t.last_time', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=315,
)

DESCRIPTOR.message_types_by_name['arena_room_t'] = _ARENA_ROOM_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

arena_room_t = _reflection.GeneratedProtocolMessageType('arena_room_t', (_message.Message,), dict(
  DESCRIPTOR = _ARENA_ROOM_T,
  __module__ = 'arena_room_db_pb2'
  # @@protoc_insertion_point(class_scope:dhc.arena_room_t)
  ))
_sym_db.RegisterMessage(arena_room_t)


# @@protoc_insertion_point(module_scope)

arena_room_t_tmp = arena_room_t

from pgame.utils import proto_utils
class arena_room_t_db(proto_utils.object_t_db):
   def __init__(self):
      proto_utils.object_t_db.__init__(self, arena_room_t_tmp)
      self.children = [
         ]

proto_utils.make_db_proto(arena_room_t_db, arena_room_t_tmp)

arena_room_t = arena_room_t_db
