# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common.proto.equip_db_pb2 as equip__db__pb2
import common.proto.pet_db_pb2 as pet__db__pb2
import common.proto.mail_db_pb2 as mail__db__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_msg.proto',
  package='protocol.common',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63ommon_msg.proto\x12\x0fprotocol.common\x1a\x0e\x65quip_db.proto\x1a\x0cpet_db.proto\x1a\rmail_db.proto\"I\n\tmsg_asset\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06value1\x18\x02 \x01(\x05\x12\x0e\n\x06value2\x18\x03 \x01(\x05\x12\x0e\n\x06value3\x18\x04 \x01(\x05\"\x8c\x01\n\nmsg_assets\x12*\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\x1a.protocol.common.msg_asset\x12\x1c\n\x06\x65quips\x18\x02 \x03(\x0b\x32\x0c.dhc.equip_t\x12\x18\n\x04pets\x18\x03 \x03(\x0b\x32\n.dhc.pet_t\x12\x1a\n\x05mails\x18\x04 \x03(\x0b\x32\x0b.dhc.mail_t\"\x1f\n\x0f\x63msg_heart_beat\x12\x0c\n\x04time\x18\x01 \x02(\x04')
  ,
  dependencies=[equip__db__pb2.DESCRIPTOR,pet__db__pb2.DESCRIPTOR,mail__db__pb2.DESCRIPTOR,])




_MSG_ASSET = _descriptor.Descriptor(
  name='msg_asset',
  full_name='protocol.common.msg_asset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protocol.common.msg_asset.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value1', full_name='protocol.common.msg_asset.value1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='protocol.common.msg_asset.value2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value3', full_name='protocol.common.msg_asset.value3', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=155,
)


_MSG_ASSETS = _descriptor.Descriptor(
  name='msg_assets',
  full_name='protocol.common.msg_assets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assets', full_name='protocol.common.msg_assets.assets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='equips', full_name='protocol.common.msg_assets.equips', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pets', full_name='protocol.common.msg_assets.pets', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mails', full_name='protocol.common.msg_assets.mails', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=298,
)


_CMSG_HEART_BEAT = _descriptor.Descriptor(
  name='cmsg_heart_beat',
  full_name='protocol.common.cmsg_heart_beat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='protocol.common.cmsg_heart_beat.time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=331,
)

_MSG_ASSETS.fields_by_name['assets'].message_type = _MSG_ASSET
_MSG_ASSETS.fields_by_name['equips'].message_type = equip__db__pb2._EQUIP_T
_MSG_ASSETS.fields_by_name['pets'].message_type = pet__db__pb2._PET_T
_MSG_ASSETS.fields_by_name['mails'].message_type = mail__db__pb2._MAIL_T
DESCRIPTOR.message_types_by_name['msg_asset'] = _MSG_ASSET
DESCRIPTOR.message_types_by_name['msg_assets'] = _MSG_ASSETS
DESCRIPTOR.message_types_by_name['cmsg_heart_beat'] = _CMSG_HEART_BEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msg_asset = _reflection.GeneratedProtocolMessageType('msg_asset', (_message.Message,), dict(
  DESCRIPTOR = _MSG_ASSET,
  __module__ = 'common_msg_pb2'
  # @@protoc_insertion_point(class_scope:protocol.common.msg_asset)
  ))
_sym_db.RegisterMessage(msg_asset)

msg_assets = _reflection.GeneratedProtocolMessageType('msg_assets', (_message.Message,), dict(
  DESCRIPTOR = _MSG_ASSETS,
  __module__ = 'common_msg_pb2'
  # @@protoc_insertion_point(class_scope:protocol.common.msg_assets)
  ))
_sym_db.RegisterMessage(msg_assets)

cmsg_heart_beat = _reflection.GeneratedProtocolMessageType('cmsg_heart_beat', (_message.Message,), dict(
  DESCRIPTOR = _CMSG_HEART_BEAT,
  __module__ = 'common_msg_pb2'
  # @@protoc_insertion_point(class_scope:protocol.common.cmsg_heart_beat)
  ))
_sym_db.RegisterMessage(cmsg_heart_beat)


# @@protoc_insertion_point(module_scope)
