# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: equip_db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='equip_db.proto',
  package='dhc',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65quip_db.proto\x12\x03\x64hc\"\xc9\x02\n\x07\x65quip_t\x12\x0c\n\x04guid\x18\x01 \x01(\x04\x12\x13\n\x0bplayer_guid\x18\x02 \x01(\x04\x12\x13\n\x0btemplate_id\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x12\n\nenchant_id\x18\n \x01(\x05\x12\x15\n\renchant_value\x18\x0b \x01(\x05\x12\x15\n\renchant_count\x18\x0c \x01(\x05\x12\x0c\n\x04\x61ttr\x18\x0e \x01(\x05\x12\r\n\x05value\x18\x0f \x01(\x05\x12\r\n\x05\x63olor\x18\x10 \x01(\x05\x12\x0f\n\x07percent\x18\x11 \x01(\x05\x12\x12\n\nattr_types\x18\x15 \x03(\x05\x12\x10\n\x08\x61ttr_ids\x18\x16 \x03(\x05\x12\x13\n\x0b\x61ttr_values\x18\x17 \x03(\x05\x12\x13\n\x0b\x61ttr_colors\x18\x18 \x03(\x05\x12\x11\n\tattr_pers\x18\x19 \x03(\x05\x12\x15\n\rreforge_count\x18\x1a \x01(\x05')
)




_EQUIP_T = _descriptor.Descriptor(
  name='equip_t',
  full_name='dhc.equip_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='dhc.equip_t.guid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_guid', full_name='dhc.equip_t.player_guid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template_id', full_name='dhc.equip_t.template_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='dhc.equip_t.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enchant_id', full_name='dhc.equip_t.enchant_id', index=4,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enchant_value', full_name='dhc.equip_t.enchant_value', index=5,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enchant_count', full_name='dhc.equip_t.enchant_count', index=6,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr', full_name='dhc.equip_t.attr', index=7,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='dhc.equip_t.value', index=8,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='dhc.equip_t.color', index=9,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent', full_name='dhc.equip_t.percent', index=10,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr_types', full_name='dhc.equip_t.attr_types', index=11,
      number=21, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr_ids', full_name='dhc.equip_t.attr_ids', index=12,
      number=22, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr_values', full_name='dhc.equip_t.attr_values', index=13,
      number=23, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr_colors', full_name='dhc.equip_t.attr_colors', index=14,
      number=24, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr_pers', full_name='dhc.equip_t.attr_pers', index=15,
      number=25, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reforge_count', full_name='dhc.equip_t.reforge_count', index=16,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=353,
)

DESCRIPTOR.message_types_by_name['equip_t'] = _EQUIP_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

equip_t = _reflection.GeneratedProtocolMessageType('equip_t', (_message.Message,), dict(
  DESCRIPTOR = _EQUIP_T,
  __module__ = 'equip_db_pb2'
  # @@protoc_insertion_point(class_scope:dhc.equip_t)
  ))
_sym_db.RegisterMessage(equip_t)


# @@protoc_insertion_point(module_scope)

equip_t_tmp = equip_t

from pgame.utils import proto_utils
class equip_t_db(proto_utils.object_t_db):
   def __init__(self):
      proto_utils.object_t_db.__init__(self, equip_t_tmp)
      self.children = [
         ]

proto_utils.make_db_proto(equip_t_db, equip_t_tmp)

equip_t = equip_t_db
