# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank_db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rank_db.proto',
  package='dhc',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rrank_db.proto\x12\x03\x64hc\"\x93\x01\n\x06rank_t\x12\x0c\n\x04guid\x18\x01 \x01(\x04\x12\x13\n\x0bplayer_guid\x18\x02 \x03(\x04\x12\x13\n\x0bplayer_name\x18\x04 \x03(\t\x12\x13\n\x0bplayer_icon\x18\x05 \x03(\x05\x12\x14\n\x0cplayer_level\x18\x06 \x03(\x05\x12\x13\n\x0bplayer_data\x18\x07 \x03(\x05\x12\x11\n\tlast_time\x18\x08 \x01(\x04')
)




_RANK_T = _descriptor.Descriptor(
  name='rank_t',
  full_name='dhc.rank_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='dhc.rank_t.guid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_guid', full_name='dhc.rank_t.player_guid', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_name', full_name='dhc.rank_t.player_name', index=2,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_icon', full_name='dhc.rank_t.player_icon', index=3,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_level', full_name='dhc.rank_t.player_level', index=4,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_data', full_name='dhc.rank_t.player_data', index=5,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_time', full_name='dhc.rank_t.last_time', index=6,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['rank_t'] = _RANK_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

rank_t = _reflection.GeneratedProtocolMessageType('rank_t', (_message.Message,), dict(
  DESCRIPTOR = _RANK_T,
  __module__ = 'rank_db_pb2'
  # @@protoc_insertion_point(class_scope:dhc.rank_t)
  ))
_sym_db.RegisterMessage(rank_t)


# @@protoc_insertion_point(module_scope)

rank_t_tmp = rank_t

from pgame.utils import proto_utils
class rank_t_db(proto_utils.object_t_db):
   def __init__(self):
      proto_utils.object_t_db.__init__(self, rank_t_tmp)
      self.children = [
         ]

proto_utils.make_db_proto(rank_t_db, rank_t_tmp)

rank_t = rank_t_db
