-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"

local RANK_T = protobuf.Descriptor();
local RANK_T_GUID_FIELD = protobuf.FieldDescriptor();
local RANK_T_PLAYER_GUID_FIELD = protobuf.FieldDescriptor();
local RANK_T_PLAYER_NAME_FIELD = protobuf.FieldDescriptor();
local RANK_T_PLAYER_ICON_FIELD = protobuf.FieldDescriptor();
local RANK_T_PLAYER_LEVEL_FIELD = protobuf.FieldDescriptor();
local RANK_T_PLAYER_DATA_FIELD = protobuf.FieldDescriptor();
local RANK_T_LAST_TIME_FIELD = protobuf.FieldDescriptor();

RANK_T_GUID_FIELD.name = "guid"
RANK_T_GUID_FIELD.full_name = ".dhc.rank_t.guid"
RANK_T_GUID_FIELD.number = 1
RANK_T_GUID_FIELD.index = 0
RANK_T_GUID_FIELD.label = 1
RANK_T_GUID_FIELD.has_default_value = false
RANK_T_GUID_FIELD.default_value = 0
RANK_T_GUID_FIELD.type = 4
RANK_T_GUID_FIELD.cpp_type = 4

RANK_T_PLAYER_GUID_FIELD.name = "player_guid"
RANK_T_PLAYER_GUID_FIELD.full_name = ".dhc.rank_t.player_guid"
RANK_T_PLAYER_GUID_FIELD.number = 2
RANK_T_PLAYER_GUID_FIELD.index = 1
RANK_T_PLAYER_GUID_FIELD.label = 3
RANK_T_PLAYER_GUID_FIELD.has_default_value = false
RANK_T_PLAYER_GUID_FIELD.default_value = {}
RANK_T_PLAYER_GUID_FIELD.type = 4
RANK_T_PLAYER_GUID_FIELD.cpp_type = 4

RANK_T_PLAYER_NAME_FIELD.name = "player_name"
RANK_T_PLAYER_NAME_FIELD.full_name = ".dhc.rank_t.player_name"
RANK_T_PLAYER_NAME_FIELD.number = 4
RANK_T_PLAYER_NAME_FIELD.index = 2
RANK_T_PLAYER_NAME_FIELD.label = 3
RANK_T_PLAYER_NAME_FIELD.has_default_value = false
RANK_T_PLAYER_NAME_FIELD.default_value = {}
RANK_T_PLAYER_NAME_FIELD.type = 9
RANK_T_PLAYER_NAME_FIELD.cpp_type = 9

RANK_T_PLAYER_ICON_FIELD.name = "player_icon"
RANK_T_PLAYER_ICON_FIELD.full_name = ".dhc.rank_t.player_icon"
RANK_T_PLAYER_ICON_FIELD.number = 5
RANK_T_PLAYER_ICON_FIELD.index = 3
RANK_T_PLAYER_ICON_FIELD.label = 3
RANK_T_PLAYER_ICON_FIELD.has_default_value = false
RANK_T_PLAYER_ICON_FIELD.default_value = {}
RANK_T_PLAYER_ICON_FIELD.type = 5
RANK_T_PLAYER_ICON_FIELD.cpp_type = 1

RANK_T_PLAYER_LEVEL_FIELD.name = "player_level"
RANK_T_PLAYER_LEVEL_FIELD.full_name = ".dhc.rank_t.player_level"
RANK_T_PLAYER_LEVEL_FIELD.number = 6
RANK_T_PLAYER_LEVEL_FIELD.index = 4
RANK_T_PLAYER_LEVEL_FIELD.label = 3
RANK_T_PLAYER_LEVEL_FIELD.has_default_value = false
RANK_T_PLAYER_LEVEL_FIELD.default_value = {}
RANK_T_PLAYER_LEVEL_FIELD.type = 5
RANK_T_PLAYER_LEVEL_FIELD.cpp_type = 1

RANK_T_PLAYER_DATA_FIELD.name = "player_data"
RANK_T_PLAYER_DATA_FIELD.full_name = ".dhc.rank_t.player_data"
RANK_T_PLAYER_DATA_FIELD.number = 7
RANK_T_PLAYER_DATA_FIELD.index = 5
RANK_T_PLAYER_DATA_FIELD.label = 3
RANK_T_PLAYER_DATA_FIELD.has_default_value = false
RANK_T_PLAYER_DATA_FIELD.default_value = {}
RANK_T_PLAYER_DATA_FIELD.type = 5
RANK_T_PLAYER_DATA_FIELD.cpp_type = 1

RANK_T_LAST_TIME_FIELD.name = "last_time"
RANK_T_LAST_TIME_FIELD.full_name = ".dhc.rank_t.last_time"
RANK_T_LAST_TIME_FIELD.number = 8
RANK_T_LAST_TIME_FIELD.index = 6
RANK_T_LAST_TIME_FIELD.label = 1
RANK_T_LAST_TIME_FIELD.has_default_value = false
RANK_T_LAST_TIME_FIELD.default_value = 0
RANK_T_LAST_TIME_FIELD.type = 4
RANK_T_LAST_TIME_FIELD.cpp_type = 4

RANK_T.name = "rank_t"
RANK_T.full_name = ".dhc.rank_t"
RANK_T.nested_types = {}
RANK_T.enum_types = {}
RANK_T.fields = {RANK_T_GUID_FIELD, RANK_T_PLAYER_GUID_FIELD, RANK_T_PLAYER_NAME_FIELD, RANK_T_PLAYER_ICON_FIELD, RANK_T_PLAYER_LEVEL_FIELD, RANK_T_PLAYER_DATA_FIELD, RANK_T_LAST_TIME_FIELD}
RANK_T.is_extendable = false
RANK_T.extensions = {}

module('rank_db_pb')

rank_t = protobuf.Message(RANK_T)

