//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Coffee_UIExtensions_UIEffectBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Coffee.UIExtensions.UIEffectBase), typeof(Coffee.UIExtensions.BaseMeshEffect));
		L.RegFunction("ModifyMaterial", ModifyMaterial);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("parameterIndex", get_parameterIndex, set_parameterIndex);
		L.RegVar("ptex", get_ptex, null);
		L.RegVar("targetGraphic", get_targetGraphic, null);
		L.RegVar("effectMaterial", get_effectMaterial, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ModifyMaterial(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Coffee.UIExtensions.UIEffectBase obj = (Coffee.UIExtensions.UIEffectBase)ToLua.CheckObject<Coffee.UIExtensions.UIEffectBase>(L, 1);
			obj.ModifyMaterial();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_parameterIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Coffee.UIExtensions.UIEffectBase obj = (Coffee.UIExtensions.UIEffectBase)o;
			int ret = obj.parameterIndex;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index parameterIndex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ptex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Coffee.UIExtensions.UIEffectBase obj = (Coffee.UIExtensions.UIEffectBase)o;
			Coffee.UIExtensions.ParameterTexture ret = obj.ptex;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ptex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_targetGraphic(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Coffee.UIExtensions.UIEffectBase obj = (Coffee.UIExtensions.UIEffectBase)o;
			UnityEngine.UI.Graphic ret = obj.targetGraphic;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetGraphic on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effectMaterial(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Coffee.UIExtensions.UIEffectBase obj = (Coffee.UIExtensions.UIEffectBase)o;
			UnityEngine.Material ret = obj.effectMaterial;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index effectMaterial on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_parameterIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Coffee.UIExtensions.UIEffectBase obj = (Coffee.UIExtensions.UIEffectBase)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.parameterIndex = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index parameterIndex on a nil value");
		}
	}
}

